name: Build Pear Desktop

on:
  push:
    branches: [master]
  pull_request:

env:
  NODE_VERSION: "24.x"

jobs:
  build:
    name: Build Pear Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup NodeJS
        if: startsWith(matrix.os, 'macOS') != true
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Setup NodeJS for macOS
        if: startsWith(matrix.os, 'macOS')
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Vite Build
        run: pnpm build

      - name: Build and release on Mac
        if: startsWith(matrix.os, 'macOS')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release:mac

      - name: Build and release on Linux
        if: startsWith(matrix.os, 'ubuntu')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install snapcraft --classic
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform/x86_64/24.08
          sudo flatpak install -y flathub org.freedesktop.Sdk/x86_64/24.08
          sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp/x86_64/24.08
          pnpm release:linux

      - name: Build and release on Windows
        if: startsWith(matrix.os, 'windows')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release:win

      - name: Test
        uses: coactions/setup-xvfb@v1
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          run: pnpm test:debug
